---
title: "Tarea_3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Abrir librerías

```{r message=FALSE, warning=FALSE}
library(dplyr)
library(DT)
library(leaflet)
library(plotly)
library(raster)
library(sf)
library(spData)
library(tidyr)
```

### Datos

```{r}
orchidaceae <-
  st_read(
    "https://raw.githubusercontent.com/gf0604-procesamientodatosgeograficos/2021i-datos/main/gbif/orchidaceae-cr-registros.csv",
    options = c(
      "X_POSSIBLE_NAMES=decimalLongitude",
      "Y_POSSIBLE_NAMES=decimalLatitude"
    ),
    quiet = TRUE
  )
```
```{r}
orchidaceae <-
  st_read(
    "https://raw.githubusercontent.com/gf0604-procesamientodatosgeograficos/2021i-datos/main/gbif/orchidaceae-cr-registros.csv",
    options = c(
      "X_POSSIBLE_NAMES=decimalLongitude",
      "Y_POSSIBLE_NAMES=decimalLatitude"
    ),
    quiet = TRUE
  )

asp <-
  st_read(
    "https://raw.githubusercontent.com/gf0604-procesamientodatosgeograficos/2021i-datos/main/sinac/asp/asp-wgs84.geojson",
    quiet = TRUE
  )
```

```{r message=FALSE, warning=FALSE}
st_crs(asp) = 4326
st_crs(orchidaceae) = 4326
```

```{r message=FALSE, warning=FALSE}
orchidaceae$species[orchidaceae$species == ""] <- "orchidaceae"
```

### Desarrollo
#### Eliminar los registros con un valor mayor que 1000

```{r message=FALSE, warning=FALSE}
orchidaceae <- orchidaceae %>%
  filter(!is.na(coordinateUncertaintyInMeters) & coordinateUncertaintyInMeters <= 1000)%>%
  filter(species!="orchidaceae")

asp <- asp %>%
  filter(descripcio!="Area Marina de Manejo" & descripcio!="Area marina protegida")
```
#### Eliminar los registros con valor vacío o NA en el campo species
```{r message=FALSE, warning=FALSE}
asp_registro <-
  asp %>%
  st_join(orchidaceae) %>%
  group_by(nombre_asp) %>%
  summarize(especies = n_distinct(species,na.rm = TRUE)) 
st_crs(asp_registro) = 4326

color_registro <-
  colorNumeric(palette = "Reds",
               domain = asp_registro$especies,
               na.color = "transparent")

color_especie <-
  colorNumeric(palette = "Reds",
               domain = asp_registro$especies,
               na.color = "transparent")
```
#### Mapa Leaflet
```{r message=FALSE, warning=FALSE}
leaflet() %>%
  addTiles(group = "OSM") %>%
  addPolygons(
    data = asp_registro,
    fillColor = ~ color_especie (asp_registro$especies),
    fillOpacity = 0.8,
    stroke = TRUE,
    color = "grey",
    weight = 1,
    popup = paste(
      paste(
        "<strong>Provincia:</strong>",
        asp_registro$nombre_asp
      ),
      paste(
        "<strong>Cantidad especie:</strong>",
        asp_registro$especies
        
      ),
      sep = '<br/>'
    ),
    group = "Provincia - especie"
  ) %>%
  addLayersControl(baseGroups = c("OSM"),
                   overlayGroups = c("Provincia - especie")) %>%
  addLegend(
    position = "bottomright",
    pal = color_especie,
    values = asp_registro$especies,
    group = "Provincia - especie",
    title = "Cantidad orquideas")      
```

